# Generated by Django 6.1.1 on 2026-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('is_attending', models.BooleanField()),
                ('guest_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
