# Generated by Django 6.1.1 on 2026-09-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='invitation_id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_sent',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_sent',
        ),
    ]
