"""
Django settings for bigday project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import re
from datetime import datetime
from zoneinfo import ZoneInfo

import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Initialise environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This is a default value and must be changed!
# Rename "localsettings.py.template" to 'localsettings.py' and edit your settings.
# To protect your credentials from leaking to your Git server we added 'localsettings.py' to the gitignore
SECRET_KEY = env('SECRET_KEY', default='this-is-something-to-change')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

# Set to "console" for console output of emails or to "smtp" to send real mails
MAIL_BACKEND = "console"

# comma-separated list of allowed hosts, e.g. "example.com,www.example.com"
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost"])
CSRF_TRUSTED_ORIGINS = [
    "http://example.com",
    'http://127.0.0.1'
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guests.apps.GuestsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bigday.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join('bigday', 'templates'),
            os.path.join('guests', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bigday.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_SERVER'),
        'PORT': env('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = 'static_root'
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join('bigday', 'static'),
)

# Some default values. Will be overwritten by a localsetting.py (rename 'localsettings.py.template' to 'localsettings.py')
# This is used in a few places where the names of the couple are used
BRIDE_AND_GROOM = env("BRIDE_AND_GROOM", default='Romeo and Juliet')
# the local date and time of your wedding, in ISO 8601 format - also drives
# the homepage countdown timer. Either leave the offset off and set
# WEDDING_TIMEZONE, or include one (e.g. '2027-05-29T16:00:00-06:00').
WEDDING_DATE = env("WEDDING_DATE", default='2027-05-29T16:00:00')
# IANA timezone name of the wedding venue, used when WEDDING_DATE has no offset
WEDDING_TIMEZONE = env("WEDDING_TIMEZONE", default='Mexico_City')
# the location of your wedding
WEDDING_LOCATION = env("WEDDING_LOCATION", default='Mexico')
# This is used in links shared around the site (e.g. the footer)
WEDDING_WEBSITE_URL = env("WEDDING_WEBSITE_URL", default='wedding.com')
# base address for all emails
DEFAULT_WEDDING_EMAIL = env("DEFAULT_WEDDING_EMAIL", default="romeaoandjuliet@email.com")

# Bank account details shown on the Gifts section, one per flag/country
# option. Each value is read from its own GIFT_* variable in '.env' (which is
# gitignored, so real details never get committed); the defaults here are
# placeholders. 'details' is a flat list of (label, value) pairs so each
# country can show whatever fields make sense for it (IBAN/SWIFT, PIX key,
# CLABE, etc). 'localsettings.py' can still override GIFT_ACCOUNTS entirely.
GIFT_ACCOUNTS = [
    {
        'flag': '🇪🇺',
        'country': 'Europe',
        'details': [
            ('Bank', env('GIFT_EU_BANK', default='Your bank name')),
            ('Account holder', env('GIFT_EU_HOLDER', default='Account holder name')),
            ('IBAN', env('GIFT_EU_IBAN', default='XX00 0000 0000 0000 0000 00')),
            ('SWIFT/BIC', env('GIFT_EU_SWIFT', default='XXXXXXXX')),
        ],
    },
    {
        'flag': '🇧🇷',
        'country': 'Brazil',
        'details': [
            ('Banco', env('GIFT_BR_BANK', default='Nome do banco')),
            ('Titular', env('GIFT_BR_HOLDER', default='Nome do titular')),
            ('Chave PIX', env('GIFT_BR_PIX', default='chave-pix@example.com')),
        ],
    },
    {
        'flag': '🇲🇽',
        'country': 'Mexico',
        'details': [
            ('Banco', env('GIFT_MX_BANK', default='Nombre del banco')),
            ('Titular', env('GIFT_MX_HOLDER', default='Nombre del titular')),
            ('CLABE', env('GIFT_MX_CLABE', default='000000000000000000')),
        ],
    },
]

# Placeholder for a future shared password guests would enter to see the
# bank details above (not enforced yet). Set it via GIFT_PASSWORD in '.env'.
GIFT_PASSWORD = env("GIFT_PASSWORD", default="")

# Checks, if the 'localsettings.py' is present and set some couple variables
# which are used in a few places.
# Otherwise it will just use some defaults above will persist.



# Normalise WEDDING_DATE to a full ISO 8601 string with a UTC offset, so the
# countdown shows the same moment for guests in every timezone (a bare time
# would be read in each visitor's local timezone). Also accepts a single-digit
# offset hour like '-6:00', which browsers reject.
_wedding_date = datetime.fromisoformat(
    re.sub(r'([+-])(\d):(\d\d)$', r'\g<1>0\2:\3', WEDDING_DATE.strip())
)
if _wedding_date.tzinfo is None:
    _wedding_date = _wedding_date.replace(tzinfo=ZoneInfo(WEDDING_TIMEZONE))
WEDDING_DATE = _wedding_date.isoformat()

if (MAIL_BACKEND == 'console'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

elif (MAIL_BACKEND == 'smtp'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Set email backend to use SMTP


# the default reply-to of your emails, change, if you want to have your replies somewhere else
DEFAULT_WEDDING_REPLY_EMAIL = DEFAULT_WEDDING_EMAIL
